curl -i -X POST \
  https://graph.facebook.com/v22.0/1087150951137933/messages \
  -H 'Authorization: Bearer EAAcLJZBSOVH8BQ0geFp3srZAAf2KSLtIFiNPAOPCIRCO1DKVTCkyf7TD12EQ77rDTO6siUFoVjcO5jYfNJDF7yKXdJltMmQmHnbvXoIJX6XH9U68z4t0ppbJZArbAUzFZB9oedLmzVzmpZCyZBele2GWk7yZByZAoXVbcRLWv8xBxYy5n1c1qGMWBJVMRZAAFskh2iZA64ALbSsfVB0AE8XumWy7cxp66QkmbYCFBggZCu6sioLMFeQZBcZCLMSvEkU42I6SxNHBLa5wWB9HO45r8HauvVM9j6UUU5OUpugZDZD' \
  -H 'Content-Type: application/json' \
  -d '{ "messaging_product": "whatsapp", "to": "2348022224166", "type": "template", "template": { "name": "hello_world", "language": { "code": "en_US" } } }'

###Registeration API

curl -X POST "https://graph.facebook.com/v22.0/1046591291866828/register" \
  -H "Authorization: Bearer EAAcLJZBSOVH8BQ5DcWmYuS5GZBbeTndVRZBaBpr8i41ErY2lrHTmiXj2GIZCm61v6Y8NxemesMmaruEt4SdZCppSS9kwNYFlgqcfxUGMVyLHB0ZC7RNXX5e0ZBePdUQTF35lurVFr7ZC4sDQaKUBEcNNJJbvmql64kCP402W0ZA5vNz4GymceoOwbbuYWIS8D0LIrozzQ9PqnHjRLSgwMXGJi6GzwOtg9TAGGJUCn" \
  -H "Content-Type: application/json" \
  -d '{
    "messaging_product": "whatsapp",
    "pin": "196300"
  }'


###Receive message webhook
  curl -X 'POST' \
  'http://localhost:8080/api/webhooks/whatsapp' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "123456789",
      "changes": [
        {
          "field": "messages",
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "1234567890",
              "phone_number_id": "123456789012345"
            },
            "contacts": [
              {
                "profile": {
                  "name": "John Doe"
                },
                "wa_id": "2348022224166"
              }
            ],
            "messages": [
              {
                "from": "2348012345678",
                "id": "wamid.HBgMNT...",
                "timestamp": "1700000000",
                "type": "text",
                "text": {
                  "body": "Hello from WhatsApp"
                }
              }
            ]
          }
        }
      ]
    }
  ]
}'


###Receive  status webhook
curl -X 'POST' \
  'http://localhost:8080/api/webhooks/whatsapp' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "123456789",
      "changes": [
        {
          "field": "messages",
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "1234567890",
              "phone_number_id": "123456789012345"
            },
            "contacts": [
              {
                "profile": {
                  "name": "John Doe"
                },
                "wa_id": "234815048728"
              }
            ],
            "messages": [
              {
                "from": "2348012345678",
                "id": "wamid.HBgMNT...",
                "timestamp": "1700000000",
                "type": "text",
                "text": {
                  "body": "Hello from WhatsApp"
                },
                "image": {
                  "id": "1234567890",
                  "mime_type": "image/jpeg",
                  "sha256": "abcdef1234567890",
                  "caption": "image caption",
                  "filename": "photo.jpg"
                },
                "document": {
                  "id": "1234567890",
                  "mime_type": "image/jpeg",
                  "sha256": "abcdef1234567890",
                  "caption": "image caption",
                  "filename": "photo.jpg"
                },
                "audio": {
                  "id": "1234567890",
                  "mime_type": "image/jpeg",
                  "sha256": "abcdef1234567890",
                  "caption": "image caption",
                  "filename": "photo.jpg"
                },
                "video": {
                  "id": "1234567890",
                  "mime_type": "image/jpeg",
                  "sha256": "abcdef1234567890",
                  "caption": "image caption",
                  "filename": "photo.jpg"
                },
                "location": {
                  "latitude": 6.5244,
                  "longitude": 3.3792,
                  "name": "Victoria Island",
                  "address": "Lagos, Nigeria"
                }
              }
            ],
            "statuses": [
              {
                "id": "wamid.HBgLMjM0ODE1MDQ4NzgyOBUCABEYEjQ2Q0M4ODVGRkI2RjYyNDc5AA==",
                "status": "delivered",
                "timestamp": "1710060212",
                "recipient_id": "2348150487828"
              }
            ]
          }
        }
      ]
    }
  ]
}'

### Send Question
curl -X 'POST' \
  'http://localhost:8080/api/channels/69aca4cd84a4eab2c5b98b3a/send-message' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "recipient": "2348022224166",
  "message": "Hello"
}'


###Send image
curl -v -X POST https://conversation-engine-5epg.onrender.com/api/channels/send-media \
  -F "channelId=69aca4cd84a4eab2c5b98b3a" \
  -F "recipient=2348022224166" \
  -F "documentType=image" \
  -F "fileName=Passport" \
  -F "file=@/Users/john/Desktop/face.png"

###Mock

  curl -X 'POST' \
  'http://localhost:8080/api/webhooks/mock' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "channelId": "69bd061c11bf835d976c4e2f",
  "from": "23412345434",
  "text": "2010-12-12"
}'