export type StepTransition = {
  event: WorkflowEventType | '*'; // e.g. ANSWER_VALID
  condition?: string; // e.g. payload.dose > 400
  nextStepId: string;
};

export enum WorkflowEventType {
  WORKFLOW_ANSWER_RECEIVED = 'WORKFLOW_ANSWER_RECEIVED',
  WORKFLOW_ASK_OPTIONS = 'WORKFLOW_ASK_OPTIONS',
  WORKFLOW_NO_OPTIONS_FOUND = 'WORKFLOW_NO_OPTIONS_FOUND',
  ANSWER_RECEIVED = 'ANSWER_RECEIVED',
  ANSWER_VALID = 'ANSWER_VALID',
  ANSWER_INVALID = 'ANSWER_INVALID',
  ACTION_COMPLETED = 'ACTION_COMPLETED',
  ACTION_FAILED = 'ACTION_FAILED',
  CONVERSATION_STOPPED = 'CONVERSATION_STOPPED',
  CONVERSATION_COMPLETED = 'CONVERSATION_COMPLETED',
  CONVERSATION_STARTED = 'CONVERSATION_STARTED',
}
